version: '3.8'

networks:
  test:
    driver: bridge

services:
  test-backend:
    extends:
      file: ./docker-compose.dev.yml
      service: backend
    container_name: test-cson-be
    ports:
      - ${APP_PORT:-3200}:3000
    networks:
      - ${NODE_ENV}
