version: '3.8'

networks:
  development:
    driver: bridge

services:
  backend:
    container_name: cson-be
    hostname: cson-be
    build:
      context: .
      target: ${NODE_ENV}
    ports:
      - ${APP_PORT:-3000}:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./node_modules:/usr/src/app/node_modules
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json:ro
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json:ro
      - ./tsconfig.json:/usr/src/app/tsconfig.json:ro
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${APP_PORT}
    restart: unless-stopped
    networks:
      - ${NODE_ENV}
    tty: true
